spring:
  application:
    name: backend
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:backend}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:change-me}
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/drumdibum}
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/drumdibum}
